---
- hosts: managed_host
  become: true
  tasks:
    - name: Build Docker image
      docker_image:
        path: /home/dockeradmin/PullCodeFromGH_BuildPipeline
        name: flaskapp_dockerized
        tag: latest
        source: build

    - name: Login to Dockerhub
      docker_login:
        username: 'deguzmancaptain@gmail.com'
        password: 'HirayaManawari@0829'

    - name: Docker tag and push to DockerHub
      docker_image:
        name: engineermarion29/flaskapp_dockerized_dh
        tag: dhremote
        source: flaskapp_dockerized:latest

    - name: Pull docker image from Dockerhub
      docker_image:
        name: docker.io/engineermarion29/flaskapp_dockerized_dh
        tag: dhremote
