apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-k8s
  labels:
    app: k8s-flaskapp

spec:
  replicas: 2
  selector:
    matchLabels: 
      app: k8s-flaskapp

  template:
    metadata:
      labels:
        app: k8s-flaskapp
    spec: 
      containers:
      - name: k8s-flaskapp
        image: engineermarion29/flaskapp_dockerized_dh:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
[root@ip-172-31-36-125 ~]# cat flaskapp_pod_manifest.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-k8s
  labels:
    app: k8s-flaskapp

spec:
  replicas: 2
  selector:
    matchLabels: 
      app: k8s-flaskapp

  template:
    metadata:
      labels:
        app: k8s-flaskapp
    spec: 
      containers:
      - name: k8s-flaskapp
        image: engineermarion29/flaskapp_dockerized_dh:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
