apiVersion: v1
kind: Service

metadata: 
  name: flask-app-k8s
  labels:
    app: k8s-flaskapp

spec:
  selector:
    app: k8s-flaskapp

  ports:
    - port: 5000
      targetPort: 5000

  type: LoadBalancer

